config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :names

  root 'welcome#index'

end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:title, :first, :last)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testruby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Names</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>First</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.title %></td>
        <td><%= name.first %></td>
        <td><%= name.last %></td>
        <td><%= link_to 'Show', name %></td>
        <td><%= link_to 'Edit', edit_name_path(name) %></td>
        <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name', new_name_path %>

app/views/names/new.html.erb
<h1>New Name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @name.title %>
</p>

<p>
  <strong>First:</strong>
  <%= @name.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @name.last %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/welcome/index.html.erb
<h1>Welcome to pauls website</h1>